version: "3"

services:
  traefik:
    image: traefik:2.4
    restart: unless-stopped
    ports:
      - "80:80"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    networks:
      internal:
        aliases:
          - ${DOMAIN}
          - api.${DOMAIN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    image: flickr-api
    container_name: api
    restart: unless-stopped
    environment:
      MONGODB_URL: mongodb://mongo
      REDIS_URL: redis://redis
      NODE_ENV: testTeam
      HOSTNAME: http://api.${DOMAIN}/
      PORT: 3000
    env_file:
      - config/e2e_test.env
    networks:
      - internal
    depends_on:
      - mongo
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=(( Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`) ) && PathPrefix(`/api`)) || Host(`api.${DOMAIN}`)
      - traefik.http.middlewares.backendPathStrip.stripprefix.prefixes=/api
      - traefik.http.middlewares.backendPathStrip.stripprefix.forceSlash=false
      - traefik.http.routers.backend.middlewares=backendPathStrip@docker

  frontend:
    image: ghcr.io/ahmedhussiien/swfrontend:latest
    container_name: frontend
    restart: unless-stopped
    logging:
      driver: none 
    networks:
      - internal
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=( Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`) )

  test:
    image: ghcr.io/ahmedhussiien/flickr-test:0036a51e
    container_name: test
    environment:
      URL: http://${DOMAIN}/
      MODE: automated
    networks:
      - internal
    depends_on:
      - api
      - frontend

  mongo:
    image: mongo:4.1.8-xenial
    container_name: mongo
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - dbdata:/data/db
    logging:
      driver: none 

  redis:
    image: redis:6.2-alpine
    container_name: redis
    networks:
      - internal
    logging:
      driver: none 

networks:
  internal:

volumes:
  dbdata: